# Generated by Django 5.1 on 2024-09-19 01:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='bg_image',
            field=models.ImageField(upload_to='images/%y/%m/%d', validators=[blog.models.validate_image_dimensions]),
        ),
    ]
